timeout: 10
default_entry: 2
interface_branding: Limine test - EFI stub (default entry 2)

/Arch - linux protocol, nokaslr
    protocol: linux
    path: boot():/vmlinuz-linux
    module_path: boot():/intel-ucode.img
    module_path: boot():/EFI/limine-nx-test/initramfs-linux.img
    cmdline: root=PARTUUID=0290f869-0320-4fdd-9a83-6a06f2285699 zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs nokaslr

/Arch - kernel EFI stub via protocol efi (default)
    protocol: efi
    path: boot():/vmlinuz-linux
    cmdline: initrd=\intel-ucode.img initrd=\EFI\limine-nx-test\initramfs-linux.img root=PARTUUID=0290f869-0320-4fdd-9a83-6a06f2285699 zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs

/Continue to systemd-boot
    protocol: efi
    path: boot():/EFI/systemd/systemd-bootx64.efi
