timeout: no
interface_branding: Limine NX test - if you can read this, Limine is running

/Limine ran on this firmware - continue to systemd-boot
    protocol: efi
    path: boot():/EFI/systemd/systemd-bootx64.efi
